version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1.0

executors:
  docker-node:
    parameters:
      version:
        default: 'lts'
        type: string
    docker:
      - image: cimg/node:<<parameters.version>>

commands:
  install:
    steps:
      - run:
          name: Install
          command: npm install
  test:
    steps:
      - run:
          name: Test
          command: npm test
  release:
    steps:
      - run:
          name: Release
          command: npx semantic-release
  lint:
    steps:
      - run:
          name: Lint
          command: npm run lint

jobs:
  test:
    resource_class: small
    parameters:
      version:
        default: 'lts'
        type: string
    executor:
      name: docker-node
      version: <<parameters.version>>
    steps:
      - checkout
      - install
      - test

  release:
    resource_class: small
    executor:
      name: docker-node
    steps:
      - checkout
      - install
      - release

  lint:
    resource_class: small
    executor:
      name: docker-node
    steps:
      - checkout
      - install
      - lint

workflows:
  test_and_release:
    jobs:
      - prodsec/secrets-scan:
          name: scan-repo
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts

      - lint:
          filters:
            branches:
              ignore:
                - master

      - test:
          matrix:
            alias: test
            parameters:
              version:
                - 14.13.0
                - 16.13.0
                - 18.16.0
          requires:
            - lint

      - release:
          context: nodejs-lib-release
          requires:
            - scan-repo
            - test
          filters:
            branches:
              only:
                - master
